# Generated by Django 5.2.16 on 2026-07-13 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('promotion_type', models.CharField(choices=[('featured', 'Featured Listing'), ('discount', 'Discount'), ('flash_sale', 'Flash Sale'), ('banner', 'Banner Ad')], default='featured', max_length=20)),
                ('boost_weight', models.PositiveSmallIntegerField(default=1, help_text='Higher = appears more prominently')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0 = no discount)', max_digits=5)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='Ad spend budget in Naira', max_digits=12)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ads_productpromotion',
                'ordering': ['-boost_weight', '-starts_at'],
            },
        ),
    ]
