# Generated by Django 5.2.17 on 2026-09-21 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundQueue",
            fields=[],
            options={
                "verbose_name": "Refund to process",
                "verbose_name_plural": "Refunds to process",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer_request", "Customer changed their mind"),
                    ("out_of_stock", "Out of stock"),
                    ("item_damaged", "Item damaged"),
                    ("payment_timeout", "Not paid within the payment window"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "No refund needed"),
                    ("due", "Refund due"),
                    ("refunded", "Refunded"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="vendor_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("allocation", "SmartMall allocation"),
                    ("stock", "Main stock"),
                ],
                default="stock",
                help_text="Which stock bucket the units were taken from, so they go back to the same place.",
                max_length=20,
            ),
        ),
    ]
