# Generated by Django 5.2.13 on 2026-05-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('orders', '0003_order_phase3_fields'),
    ]

    operations = [
    ]
