# Generated by Django 5.2.17 on 2026-09-22 10:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_order_business(apps, schema_editor):
    """Existing orders: set the shop from their first item."""
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    for order in Order.objects.filter(business__isnull=True):
        item = OrderItem.objects.filter(order=order).select_related("product").first()
        if item:
            order.business_id = item.product.business_id
            order.save(update_fields=["business"])


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_business_address_business_legal_name_and_more"),
        ("orders", "0003_order_cancellation_refunds_stock_holds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop_orders",
                to="businesses.business",
            ),
        ),
        migrations.CreateModel(
            name="CheckoutGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkout_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders_checkoutgroup",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="checkout_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.checkoutgroup",
            ),
        ),
        migrations.RunPython(backfill_order_business, migrations.RunPython.noop),
    ]
