"""
Application constants for the businesses app.
"""

MAX_BUSINESS_NAME_LENGTH = 255
MAX_PHONE_LENGTH = 30
DEFAULT_COUNTRY = "Nigeria"

DEFAULT_DELIVERY_RADIUS_KM = 5
DEFAULT_PREPARATION_TIME = 30

MAX_RATING = 5
MIN_RATING = 1

DEFAULT_CURRENCY = "NGN"