# Generated by Django 5.2.16 on 2026-07-13 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('vendor_managed', 'Vendor managed'), ('partner', 'Logistics partner')], max_length=32)),
                ('partner', models.CharField(blank=True, choices=[('gig', 'GIG Logistics'), ('kwik', 'Kwik Delivery'), ('dhl', 'DHL')], max_length=32)),
                ('tracking_number', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('packaging', 'Packaging'), ('pickup', 'Pickup'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='pending', max_length=32)),
            ],
            options={
                'db_table': 'delivery_shipment',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('packaging', 'Packaging'), ('pickup', 'Pickup'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'delivery_trackingevent',
                'ordering': ['-created_at'],
            },
        ),
    ]
