# Generated by Django 5.2.13 on 2026-05-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        ('delivery', '0003_tracking_event'),
    ]

    operations = [
    ]
