# Generated by Django 5.2.16 on 2026-07-13 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Menu', help_text="e.g. 'Lunch Menu', 'Full Menu'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='businesses.business')),
            ],
            options={
                'db_table': 'dining_menu',
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Starters, Mains, Drinks', max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower number shows first.')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dining.menu')),
            ],
            options={
                'db_table': 'dining_menu_section',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dining/menu_items/')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to temporarily hide from customers (e.g. sold out today).')),
                ('dietary_flags', models.JSONField(blank=True, default=list, help_text="List of dietary flags e.g. ['halal', 'spicy']")),
                ('preparation_minutes', models.PositiveSmallIntegerField(default=15, help_text='Estimated preparation time in minutes.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dining.menusection')),
            ],
            options={
                'db_table': 'dining_menu_item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Reservation date.')),
                ('time', models.TimeField(help_text='Reservation time.')),
                ('party_size', models.PositiveSmallIntegerField(help_text='Number of guests.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='e.g. window seat, birthday cake, wheelchair access.')),
                ('rejection_reason', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='businesses.business')),
            ],
            options={
                'db_table': 'dining_reservation',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
