# Generated by Django 5.2.17 on 2026-10-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productembedding_productimage_productvariant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="low_stock_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the shop was last told this item is running low. Set on the way down and cleared once it is restocked above the threshold, so a shop is told once per fall rather than every time the checker runs.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Tell the shop when available stock falls to this number or below.",
            ),
        ),
    ]
