# Generated by Django 5.2.16 on 2026-07-13 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(help_text='Business that owns this branch.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_business_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_business_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessgallery',
            name='business',
            field=models.ForeignKey(help_text='Business this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='branch',
            field=models.ForeignKey(help_text='Branch these operating hours belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='businesses.branch'),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave empty if the member serves all branches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='businesses.branch'),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='business',
            field=models.ForeignKey(help_text='Business the member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='User that invited this member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='user',
            field=models.ForeignKey(help_text='User assigned to this business.', on_delete=django.db.models.deletion.PROTECT, related_name='business_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessrating',
            name='business',
            field=models.ForeignKey(help_text='Business being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessrating',
            name='customer',
            field=models.ForeignKey(help_text='Customer who submitted the review.', on_delete=django.db.models.deletion.CASCADE, related_name='business_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessverification',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='branch',
            field=models.ForeignKey(help_text='Branch this delivery zone belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='businesses.branch'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='business',
            field=models.OneToOneField(help_text='Restaurant business.', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to='businesses.business'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['business'], name='businesses__busines_476347_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['city'], name='businesses__city_848b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['state'], name='businesses__state_87823a_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['country'], name='businesses__country_f4ad4e_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='businesses__is_acti_57af19_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['created_at'], name='businesses__created_7c5353_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_branch_name_per_business'),
        ),
        migrations.AddIndex(
            model_name='businessgallery',
            index=models.Index(fields=['business'], name='businesses__busines_c12970_idx'),
        ),
        migrations.AddIndex(
            model_name='businessgallery',
            index=models.Index(fields=['display_order'], name='businesses__display_7aea97_idx'),
        ),
        migrations.AddIndex(
            model_name='businessgallery',
            index=models.Index(fields=['is_active'], name='businesses__is_acti_4de6f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessgallery',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('business',), name='unique_business_cover_image'),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['branch'], name='businesses__branch__13385f_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['weekday'], name='businesses__weekday_3ffd2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.UniqueConstraint(fields=('branch', 'weekday'), name='unique_branch_weekday'),
        ),
        migrations.AddIndex(
            model_name='businesslocation',
            index=models.Index(fields=['city'], name='businesses__city_c1671a_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslocation',
            index=models.Index(fields=['state'], name='businesses__state_6982fe_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslocation',
            index=models.Index(fields=['country'], name='businesses__country_248b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['business'], name='businesses__busines_28cf26_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['branch'], name='businesses__branch__09ec3c_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['user'], name='businesses__user_id_8b68d2_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['role'], name='businesses__role_4b6a59_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['status'], name='businesses__status_2f032d_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmember',
            index=models.Index(fields=['created_at'], name='businesses__created_46ee56_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessmember',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='unique_business_member'),
        ),
        migrations.AddIndex(
            model_name='businessrating',
            index=models.Index(fields=['business'], name='businesses__busines_ad797c_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrating',
            index=models.Index(fields=['customer'], name='businesses__custome_939c44_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrating',
            index=models.Index(fields=['score'], name='businesses__score_69e289_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrating',
            index=models.Index(fields=['is_visible'], name='businesses__is_visi_ba4fad_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrating',
            index=models.Index(fields=['created_at'], name='businesses__created_7053c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessrating',
            constraint=models.UniqueConstraint(fields=('business', 'customer'), name='unique_customer_business_rating'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['branch'], name='businesses__branch__95f445_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['name'], name='businesses__name_0462ac_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['is_active'], name='businesses__is_acti_987b58_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_delivery_zone_per_branch'),
        ),
        migrations.AddIndex(
            model_name='restaurantprofile',
            index=models.Index(fields=['business'], name='businesses__busines_830c83_idx'),
        ),
    ]
