# Generated by Django 5.2.16 on 2026-08-02 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='business',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='business',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='business',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='businesses__owner_i_7abb69_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category'], name='businesses__categor_6edb76_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='businesses__status_94f785_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='businesses__name_a138ad_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['created_at'], name='businesses__created_34b472_idx'),
        ),
    ]
