# Generated by Django 5.2.13 on 2026-05-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='business',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered legal name for verification.', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business / company registration number.', max_length=128),
        ),
        migrations.AddField(
            model_name='business',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_identifier',
            field=models.CharField(blank=True, help_text='Tax ID / VAT where applicable.', max_length=64),
        ),
        migrations.AddField(
            model_name='business',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
    ]
