# Generated by Django 5.2.17 on 2026-09-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_business_address_business_legal_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="delivers",
            field=models.BooleanField(
                default=False,
                help_text="Does this shop deliver to customers in its area?",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Flat fee this shop charges for delivery.",
                max_digits=10,
            ),
        ),
    ]
